### ISSUE TITLE
Problem of deflation verification in soar.py

### ISSUE THREAD

**Issue by pan3rock** [LucasKulaska/soar_dynamics#1]
When I try example 1 in paper[1], 
![Screenshot_20200604_123253](https://user-images.githubusercontent.com/44249464/83715432-e5755f80-a65f-11ea-97f9-50a1ec05d2c5.png)

I encounter a problem:
```
Traceback (most recent call last):
  File "soar.py", line 144, in <module>
    Q, T, P, deflation = soar.procedure(n = n)
  File "soar.py", line 114, in procedure
    if norm(f_proj) > tol:
UnboundLocalError: local variable 'f_proj' referenced before assignment

```

The input for example 1 in paper[1]
```python
    M = np.eye(N, N) * 0.1
    D = np.eye(N, N)
    K = np.eye(N, N) * 0.2
    # K[-1, -1] = 0.1
    for i in range(1, N):
        K[i, i-1] = -0.1
        K[i-1, i] = -0.1
    A = -inv(M) * D
    B = -inv(M) * K

```
I have tried some fixes but the ` norm( Q.T @ Q - np.eye(n) )` didn't equal to zero. Maybe I don't understand the paper correctly. Could you please fix the part of codes?
![Screenshot_20200604_123948](https://user-images.githubusercontent.com/44249464/83715648-86fcb100-a660-11ea-83ad-bba1f9bbfc8d.png)

**Comment by LucasKulaska** [comment]
The deflation and breakdown deflation isn't ok yet. I have to figure out a not too computational expansive way to do it.
